QUERY_NUMBER: 200 #limit the size of the dataset
TOPN_ITEMS: 500
TOPK_ITEMS: 10
#DOMAIN: "amazon_clothing"
#DOMAIN: "amazon_beauty"
DOMAIN: "kdd22"

MODEL: "gpt-4o-2024-08-06"
#MODEL: "claude-3-5-sonnet-20240620"
#MODEL: "qwen-plus-2024-09-19"

METHOD: "TAIRA"

OPENAI_BASE_URL: "https://api.openai.com/v1"
OPENAI_API_KEY: "sk-"

GOOGLE_API_KEY: ""
GOOGLE_CSE_ID: ""